version: "2"
services:

  vertcoind:
    image: lukechilds/vertcoind
    expose:
      - "8332"
    ports:
      - "8333:8333"
    volumes:
      - ./data/vertcoind:/data
    command: -rpcuser=middleware -rpcpassword=middleware -txindex

  vtc-middleware-cpp:
    image: vtc-wallet-middleware
    expose:
      - "8888"
    volumes:
      - ./data/vertcoind/blocks:/blocks
      - ./data/index:/tmp/testdb
